[project]
name = "call-me-maybe"
version = "0.1.0"
description = "A function calling engine that turns natural language prompts into JSON function calls using token-level decoding."
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"
authors = [
    { name = "Daniel Filipe Moreira Fernandes", email = "danmorei@student.codam.nl" },
]
dependencies = [
    "numpy>=2.0",
    "pydantic>=2.0",
]

[dependecy-groups]
dev = [
    "flake8>=7.0",
    "mypy>=1.10",
    "pytest>=8.0",
]

[tool.uv]
package = false

[tool.mypy]
python_version = "3.10"
exclude = ['^\.venv/', '^llm_sdk/']
