[project]
name = "fly-in"
version = "0.1.0"
description = "Route a fleet of drones from start to end through a zone network."
readme = "README.md"
authors = [
    { name = "Daniel Filipe Moreira Fernandes", email = "danmorei@student.codam.nl" }
]
requires-python = ">=3.10"
dependencies = [
    "pygame-ce>=2.5.8",
]

[dependency-groups]
dev = [
    "flake8>=7.4.1",
    "mypy>=2.4.0",
]
